version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - C:\Docker\Data\pg-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - main

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - C:\Docker\Data\pg-admin4:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - main
networks:
  main:
